apiVersion: v1
kind: Service
metadata:
  name: project8-frontend-service
spec:
  selector:
    app: project8-frontend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
