apiVersion: v1
kind: Pod
metadata:
  name: siddhantops-load-generator
  labels:
    owner: ayush-siddhant
    prn: "23070122066"
spec:
  containers:
    - name: load-generator
      image: busybox:latest
      command:
        - /bin/sh
        - -c
        - |
          while true; do
            wget -q -O- http://siddhantops-service;
          done
  restartPolicy: Always
