apiVersion: v1
kind: Secret
metadata:
  name: shopsphere-secret
  namespace: microservices-demo
  labels:
    app.kubernetes.io/part-of: shopsphere
type: Opaque
stringData:
  DB_USERNAME: "shopsphere_admin"
  DB_PASSWORD: "K8sSecureOrderPassword2026!"
  API_SECRET: "jwt-mesh-secret-token-key-23070122063"
