apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: microservices-demo
  labels:
    app: user-service
    app.kubernetes.io/part-of: shopsphere
    app.kubernetes.io/component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        app.kubernetes.io/part-of: shopsphere
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: user-service
          image: shopsphere-user-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          envFrom:
            - configMapRef:
                name: shopsphere-config
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
