FROM jenkins/jenkins:lts-jdk17

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        gnupg \
        python3 \
        python3-pip \
        openssh-client \
        maven \
        git \
    && install -m 0755 -d /etc/apt/keyrings \
    && curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc \
    && chmod a+r /etc/apt/keyrings/docker.asc \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable" > /etc/apt/sources.list.d/docker.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends docker-ce-cli \
    && rm -rf /var/lib/apt/lists/* \
    && usermod -aG root jenkins

ENV PIP_BREAK_SYSTEM_PACKAGES=1
ENV DOCKER_HOST=unix:///var/run/docker.sock
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false -Dorg.apache.commons.jelly.tags.fmt.timeZone=Asia/Kolkata"
ENV CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yaml

COPY jenkins-docker-entrypoint.sh /usr/local/bin/jenkins-docker-entrypoint.sh
RUN sed -i 's/\r$//' /usr/local/bin/jenkins-docker-entrypoint.sh \
    && chmod +x /usr/local/bin/jenkins-docker-entrypoint.sh

USER jenkins
RUN jenkins-plugin-cli --plugins \
    git \
    workflow-aggregator \
    configuration-as-code \
    ssh-slaves \
    credentials \
    credentials-binding \
    ws-cleanup \
    junit \
    pipeline-stage-view

USER root
ENTRYPOINT ["/usr/local/bin/jenkins-docker-entrypoint.sh"]
